import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    paddingVertical: 18,
    paddingHorizontal: 16,
    backgroundColor: "#fff",
    paddingBottom: 20,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  greetingRow: {
    alignItems: "center",
    marginBottom: 8,
  },
  greetingText: {
    fontSize: 32,
    fontWeight: "700",
  },
  quickSection: {
    marginTop: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
    marginLeft: 4,
  },
  buttonsGrid: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickButton: {
    backgroundColor: "#466CA5",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 8,
    width: "48%",
    alignItems: "center",
  },
  quickButtonText: {
    color: "#fff",
    fontWeight: "600",
    textAlign: "center",
    fontSize: 20,
  },
  apartmentSection: {
    marginTop: 12,
  },
  apartmentCard: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingBlock: 8,
    backgroundColor: "#fafafa",
    borderColor: "#e2e2e2",
    borderWidth: 1,
  },
  apartmentTitle: {
    fontSize: 26,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
  },
  fieldRow: {
    flexDirection: "column",
    justifyContent: "flex-start",
    marginBottom: 6,
  },
  fieldLabel: {
    fontWeight: "600",
    marginBottom: 6,
  },
  fieldValue: {
    width: "100%",
    fontSize: 16,
    textAlign: "left",
    backgroundColor: "white",
    borderColor: "#747474",
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingBlock: 4,
  },
  moradoresGrid: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
  },
  moradorCard: {
    width: "45%",
    backgroundColor: "#466CA5",
    padding: 10,
    borderRadius: 10,
    marginBottom: 12,
    alignItems: "center",
    marginHorizontal: 5,
  },
  avatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    marginBottom: 8,
  },
  moradorName: {
    color: "#fff",
    fontWeight: "700",
    textAlign: "center",
  },
  moradorDoc: {
    color: "#fff",
    fontSize: 12,
    marginTop: 6,
  },
  moradorPhone: {
    color: "#fff",
    fontSize: 12,
  },
  moradorAge: {
    color: "#fff",
    fontSize: 12,
    marginTop: 6,
  },
  bellFab: {
    position: "absolute",
    right: 18,
    bottom: 32,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#343346",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 99,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 6,
  },
  bellIcon: {
    color: "#fff",
    fontSize: 20,
  },
  userImg: {
    width: "100%",
    height: "100%",
  },
});
